apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: prshop
          image: kamil1520/prshop
          ports:
            - containerPort: 8080
          env:
            - name: PGSQL_URL
              value: jdbc:postgresql://postgres:5432/mydb
            - name: PGSQL_USER
              value: root
            - name: PGSQL_PASSWORD
              value: root
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort

  