version: "3"
services:
  springboot-app:
    image: prshop
    build: .
    ports:
      - 8080:8080
    environment:
      PGSQL_URL: jdbc:postgresql://db:5432/my_db
      PGSQL_USER: root
      PGSQL_PASSWORD: root
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:

